import type { EventItem, FaceData, HistoryEvent, Script } from './types'

export const scripts: Script[] = [
  {
    id: 'helmet',
    name: 'Safety Helmet Detection',
    meta: 'People · Helmet · No helmet',
    loaded: true,
    cameras: ['Site Entrance Camera', 'Warehouse Camera', 'Demo Camera'],
    kpis: [
      ['People detected', '8', '+2 today'],
      ['Wearing helmet', '6', '75% compliance'],
      ['No helmet', '2', 'Needs attention'],
      ['Active violations', '2', 'Latest 10:32:15'],
    ],
  },
  {
    id: 'people',
    name: 'People Counting',
    meta: 'Count · Entry · Exit',
    loaded: true,
    cameras: ['Site Entrance Camera', 'Warehouse Camera'],
    kpis: [
      ['Current people', '8', 'In selected zone'],
      ['Entered today', '42', '+6 in last hour'],
      ['Exited today', '35', 'Normal flow'],
      ['Occupancy', 'Normal', 'Below threshold'],
    ],
  },
  {
    id: 'face',
    name: 'Face Recognition',
    meta: 'Recognized · Unknown · Database',
    loaded: false,
    cameras: ['Site Entrance Camera', 'Demo Camera'],
    description: 'Real-time facial recognition with detection boxes and name labels. Processes every 10th frame for performance.',
    kpis: [
      ['Faces detected', '4', 'Current frame'],
      ['Recognized', '3', 'Registered people'],
      ['Unknown', '1', 'Review event'],
      ['Confidence', '94%', 'Average'],
    ],
    params: [
      {
        key: 'FACE_DISTANCE_THRESHOLD',
        label: 'Face Match Threshold',
        value: 0.3,
        min: 0.1,
        max: 0.8,
        step: 0.05,
        type: 'float',
        description: 'Maximum distance to consider a face match (lower = stricter, better accuracy)',
      },
      {
        key: 'ALERT_COOLDOWN',
        label: 'Alert Cooldown',
        value: 10,
        min: 5,
        max: 300,
        step: 1,
        type: 'number',
        description: 'Seconds between alerts for the same person',
      },
    ],
    videoSource: 'rtsp://admin:varadise888@192.168.51.253:554/cam/realmonitor?channel=1&subtype=0',
    rtmpOutput: 'rtmp://cctv-ai-uat.varadise.cloud:1936/group/grQKLloOUX?token=EPICDJMGMP',
  },
  {
    id: 'traffic',
    name: 'Traffic Counting',
    meta: 'Vehicles · Pedestrians · Direction',
    loaded: false,
    cameras: ['Warehouse Camera', 'Demo Camera'],
    kpis: [
      ['Vehicles detected', '12', 'Current zone'],
      ['Pedestrians', '9', 'Current zone'],
      ['Passed today', '79', 'Across counting line'],
      ['Traffic status', 'Normal', 'Below threshold'],
    ],
  },
]

export const events: EventItem[] = [
  {
    time: '10:32:15',
    camera: 'Site Entrance Camera',
    script: 'Safety Helmet Detection',
    name: 'No helmet detected',
    meta: 'Person #04 · Restricted work zone',
    confidence: '92%',
    ok: false,
  },
  {
    time: '10:31:48',
    camera: 'Warehouse Camera',
    script: 'Safety Helmet Detection',
    name: 'Person entered zone',
    meta: 'Restricted work zone',
    confidence: '88%',
    ok: false,
  },
  {
    time: '10:30:22',
    camera: 'Demo Camera',
    script: 'Safety Helmet Detection',
    name: 'Helmet detected',
    meta: 'Person #02',
    confidence: '96%',
    ok: true,
  },
  {
    time: '10:29:11',
    camera: 'Site Entrance Camera',
    script: 'People Counting',
    name: 'Person entered zone',
    meta: 'Main entrance · Direction: in',
    confidence: '91%',
    ok: true,
  },
  {
    time: '10:27:03',
    camera: 'Warehouse Camera',
    script: 'People Counting',
    name: 'Occupancy threshold normal',
    meta: 'Warehouse aisle · 8 people',
    confidence: '89%',
    ok: true,
  },
]

export const historyEvents: HistoryEvent[] = [
  {
    date: '2026-09-08',
    time: '09:14:02',
    camera: 'Site Entrance Camera',
    script: 'Safety Helmet Detection',
    name: 'No helmet detected',
    meta: 'Person #11 · Restricted work zone',
    confidence: '90%',
    ok: false,
  },
  {
    date: '2026-09-08',
    time: '11:47:35',
    camera: 'Warehouse Camera',
    script: 'Safety Helmet Detection',
    name: 'Helmet detected',
    meta: 'Person #06',
    confidence: '95%',
    ok: true,
  },
  {
    date: '2026-09-09',
    time: '08:22:10',
    camera: 'Site Entrance Camera',
    script: 'Safety Helmet Detection',
    name: 'No helmet detected',
    meta: 'Person #03 · Restricted work zone',
    confidence: '88%',
    ok: false,
  },
  {
    date: '2026-09-09',
    time: '14:05:51',
    camera: 'Demo Camera',
    script: 'Safety Helmet Detection',
    name: 'Helmet detected',
    meta: 'Person #09',
    confidence: '97%',
    ok: true,
  },
  {
    date: '2026-09-10',
    time: '10:30:22',
    camera: 'Warehouse Camera',
    script: 'Safety Helmet Detection',
    name: 'Person entered zone',
    meta: 'Restricted work zone',
    confidence: '86%',
    ok: false,
  },
  {
    date: '2026-09-08',
    time: '10:02:18',
    camera: 'Site Entrance Camera',
    script: 'People Counting',
    name: 'Person entered zone',
    meta: 'Main entrance · Direction: in',
    confidence: '92%',
    ok: true,
  },
  {
    date: '2026-09-09',
    time: '16:41:07',
    camera: 'Warehouse Camera',
    script: 'People Counting',
    name: 'Occupancy threshold normal',
    meta: 'Warehouse aisle · 11 people',
    confidence: '90%',
    ok: true,
  },
  {
    date: '2026-09-10',
    time: '09:33:44',
    camera: 'Site Entrance Camera',
    script: 'People Counting',
    name: 'Person exited zone',
    meta: 'Main entrance · Direction: out',
    confidence: '89%',
    ok: true,
  },
]

export const initialFaceData: FaceData[] = [
  { id: 1, name: 'Alex Chen', imageName: 'face_0001.jpg', image: 'https://i.pravatar.cc/96?img=12' },
  { id: 2, name: 'Jordan Lee', imageName: 'face_0002.jpg', image: 'https://i.pravatar.cc/96?img=32' },
  { id: 3, name: 'Unknown Reference', imageName: 'face_0003.jpg', image: 'https://i.pravatar.cc/96?img=49' },
]

export const cameraStatus: Record<string, 'online' | 'offline'> = {
  'Site Entrance Camera': 'online',
  'Warehouse Camera': 'online',
  'Demo Camera': 'offline',
}

export const cameraInputs: Record<string, string> = {
  'Site Entrance Camera': 'rtmp://demo.cosmos.local/site-entrance',
  'Warehouse Camera': 'rtmp://demo.cosmos.local/warehouse',
  'Demo Camera': 'rtmp://demo.cosmos.local/demo',
}
